"""
List of models
"""

from enum import Enum

class ModelList(Enum):
    LOGI = "logi"
    RECT = "rect"
    TransE = "TransE"
    TransE_m1 = "TransE_m1"
    TransE_m3 = "TransE_m3"
    TransE_m3_1 = "TransE_m3_1"
    TransE_m3_3 = "TransE_m3_3"
    DistMult = "DistMult"
    DistMult_m1 = "DistMult_m1"
    DistMult_m2 = "DistMult_m2"
    ComplEx = "ComplEx"
    ComplEx_m1 = "ComplEx_m1"
    ComplEx_m1_1 = "ComplEx_m1_1"
    ComplEx_m3 = "ComplEx_m3"
    ComplEx_m4 = "ComplEx_m4"
    ComplEx_m5_1 = "ComplEx_m5_1"
    ComplEx_m5_2 = "ComplEx_m5_2"
    ComplEx_m5_3 = "ComplEx_m5_3"
    ComplEx_m5_4 = "ComplEx_m5_4"
    ComplEx_m6_1 = "ComplEx_m6_1"
    ComplEx_m6_2 = "ComplEx_m6_2"
    ComplEx_m7 = "ComplEx_m7"
    ComplEx_m8 = "ComplEx_m8"
    ComplEx_m9_1 = "ComplEx_m9_1"
    ComplEx_m9_2 = "ComplEx_m9_2"
    ComplEx_m9_3 = "ComplEx_m9_3"
    ComplEx_m10 = "ComplEx_m10"
    ComplEx_m10_1 = "ComplEx_m10_1"
    ComplEx_m10_2 = "ComplEx_m10_2"
    ComplEx_m10_3 = "ComplEx_m10_3"
    ComplEx_m10_4 = "ComplEx_m10_4"
    RotatE = "RotatE"
    RotatE_m1 = "RotatE_m1"
    RotatE_m2 = "RotatE_m2"
    RotatE_m2_1 = "RotatE_m2_1"
    RotatE_m2_2 = "RotatE_m2_2"
    RotatE_m3 = "RotatE_m3"
    RotatE_m3_1 = "RotatE_m3_1"
    RotatE_m3_2 = "RotatE_m3_2"
    RotatE_m3_3 = "RotatE_m3_3"
    RotatE_m4 = "RotatE_m4"
    RotatE_m5 = "RotatE_m5"
    RotatE_m5_1 = "RotatE_m5_1"
    UKGE_logi_m1 = "UKGE_logi_m1"
    UKGE_logi_m2 = "UKGE_logi_m2"
    DistMult_VAE = "DistMult_VAE"
    DistMult_VAE_Contrastive = "DistMult_VAE_Contrastive"
    KEGCN_DistMult = "KEGCN_DistMult"
    
